"""Arc Market Structure Event Radar Engine (T33)

Consumes canonical MarketStructureEvent instances and maps them to priority recalculation queues:
- Enforces zero automated buy orders across all event types
- Links event affected tokens to candidate arbitrage routes
- Outputs verifiable RadarEventReport
"""

from __future__ import annotations

import time
from dataclasses import dataclass
from typing import Any

from arbitrage_contracts.arc_extensions import MarketStructureEvent
from arbitrage_contracts.quote import RouteRef
from arc_research.events.rules import (
    EventAction,
    EventEvaluationRules,
    EventRuleDecision,
    MarketEventType,
    PriorityLevel,
)


@dataclass(frozen=True, slots=True)
class RadarEventReport:
    """Actionable report generated by the market structure event radar."""

    event_id: str
    event_type: str
    priority: PriorityLevel
    action: EventAction
    affected_tokens: tuple[str, ...]
    affected_routes_count: int
    affected_route_ids: tuple[str, ...]
    buy_order_emitted: bool = False
    details: dict[str, Any] | None = None
    processed_at_utc: float = 0.0


class MarketEventRadar:
    """Radar engine monitoring second venues, migrations, and curve lifecycle events."""

    def __init__(self, candidate_routes: list[RouteRef] | None = None) -> None:
        self._routes = candidate_routes or []
        self._known_pools: dict[str, dict[str, str]] = {}  # token_pair_key -> {venue: pool_addr}

    def register_known_pool(self, token_a: str, token_b: str, venue: str, pool_address: str) -> None:
        """Record an established pool for venue deduplication."""
        pair_key = self._make_pair_key(token_a, token_b)
        if pair_key not in self._known_pools:
            self._known_pools[pair_key] = {}
        self._known_pools[pair_key][venue] = pool_address.lower()

    def process_event(self, event: MarketStructureEvent) -> RadarEventReport:
        """Process a MarketStructureEvent and determine recalculation scope."""
        details_dict = dict(event.details)
        event_type_str = event.event_type

        # Dispatch rule evaluation
        decision: EventRuleDecision
        if event_type_str == MarketEventType.SECOND_VENUE_CREATED:
            t0 = event.affected_assets[0] if len(event.affected_assets) > 0 else ""
            t1 = event.affected_assets[1] if len(event.affected_assets) > 1 else ""
            pair_key = self._make_pair_key(t0, t1)
            existing_pools = self._known_pools.get(pair_key, {})
            new_venue = details_dict.get("venue_name", "unknown_venue")
            new_pool = details_dict.get("pool_address", event.pool_id or "")

            decision = EventEvaluationRules.evaluate_second_venue(
                token_a=t0,
                token_b=t1,
                existing_venue_pools=existing_pools,
                new_venue_name=new_venue,
                new_pool_address=new_pool,
            )
            if decision.is_valid_second_venue:
                self.register_known_pool(t0, t1, new_venue, new_pool)

        elif event_type_str == MarketEventType.GRADUATION_MILESTONE:
            curve_addr = details_dict.get("curve_pool_address", event.pool_id or "")
            t_addr = event.affected_assets[0] if event.affected_assets else ""
            progress = details_dict.get("bonding_progress_bps", 0)
            decision = EventEvaluationRules.evaluate_graduation_milestone(
                curve_pool_address=curve_addr,
                token_address=t_addr,
                bonding_progress_bps=progress,
            )

        elif event_type_str == MarketEventType.LIQUIDITY_MIGRATED:
            src = details_dict.get("source_curve_address", "")
            dst = details_dict.get("target_amm_address", "")
            t_addr = event.affected_assets[0] if event.affected_assets else ""
            decision = EventEvaluationRules.evaluate_liquidity_migrated(
                source_curve_address=src,
                target_amm_address=dst,
                token_address=t_addr,
            )
        else:
            decision = EventRuleDecision(
                event_type=MarketEventType.LIQUIDITY_CHANGED,
                priority=PriorityLevel.NORMAL,
                action=EventAction.RECALCULATE_PRIORITY,
                affected_tokens=tuple(a.lower() for a in event.affected_assets),
                is_valid_second_venue=False,
                confidence_score=0.8,
                audit_notes=("Standard liquidity change event",),
            )

        # Match affected candidate routes by token address
        matched_routes: list[str] = []
        token_set = set(decision.affected_tokens)
        for r in self._routes:
            # Check if route touches any affected token
            for hop in r.hops:
                hop_in = hop.asset_in.token_key.address if hop.asset_in.token_key else ""
                hop_out = hop.asset_out.token_key.address if hop.asset_out.token_key else ""
                if hop_in.lower() in token_set or hop_out.lower() in token_set:
                    matched_routes.append(r.route_id)
                    break

        return RadarEventReport(
            event_id=event.event_id,
            event_type=event.event_type,
            priority=decision.priority,
            action=decision.action,
            affected_tokens=decision.affected_tokens,
            affected_routes_count=len(matched_routes),
            affected_route_ids=tuple(sorted(set(matched_routes))),
            buy_order_emitted=False,  # Permanently False
            details=details_dict,
            processed_at_utc=time.time(),
        )

    def _make_pair_key(self, token_a: str, token_b: str) -> str:
        sorted_tokens = sorted([token_a.lower(), token_b.lower()])
        return f"{sorted_tokens[0]}:{sorted_tokens[1]}"
