"""Independent regression test suite for legacy Uniswap V4 PoolKey obligations in Arc.

Migrated from legacy tests/test_v4_poolkey.py (Phase 1 remediation).
Key obligations verified:
1. Exact EVM Keccak-256 derivation across all 6 canonical test vectors (full 66-character hashes).
2. Mathematical proof of NIST SHA3-256 divergence and defect isolation.
3. Field sensitivity across all 5 PoolKey components.
4. Address casing normalization and invariance.
5. Strict fail-closed currency ordering invariant (currency0 < currency1).
6. Parameter bounds (fee uint24, tick_spacing positive int24).
7. Dynamic fee and custom hook qualification attributes.
8. Case-insensitive pool discovery lookup and manager authorization gating.
"""

from __future__ import annotations

import hashlib

import pytest
from eth_abi.abi import encode as independent_abi_encode
from eth_utils.crypto import keccak as independent_keccak

from arc_markets.deployments import (
    ArcDeploymentRecord,
    ContractRole,
    DeploymentsRegistry,
)
from arc_markets.v4_discovery import (
    V4DiscoveredPool,
    V4MarketDiscoveryEngine,
)
from arc_markets.v4_events import (
    DYNAMIC_FEE_FLAG,
    V4InitializeEvent,
    V4PoolKey,
)
from arc_readiness.errors import (
    ArcMarketIneligibleError,
    ArcValidationError,
)

# ---------------------------------------------------------------------------
# Canonical Test Vectors (migrated verbatim from legacy tests/test_v4_poolkey.py)
# Token addresses are pure algorithmic 20-byte inputs; they are NOT registered in Arc chain 5042 deployments.
# Expected poolIds are fixed on-chain canonical EVM keccak256(abi.encode(...)) values, NOT generated by compute_pool_id().
# ---------------------------------------------------------------------------
LEGACY_SIX_CANONICAL_VECTORS = [
    (
        "ai_usdg_023",
        "0x2E8c31162b855A2ffa90F6F8634643Ad6F111e18",
        "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168",
        2300,
        23,
        "0x0000000000000000000000000000000000000000",
        "0x7aebd80541bfaaf23dbb6e99ce13d4d31c1a84c91414f971eadbff7db5f85995",
    ),
    (
        "pons_usdg_03",
        "0x39dBED3a2bd333467115dE45665cC57F813C4571",
        "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168",
        3000,
        60,
        "0x0000000000000000000000000000000000000000",
        "0x4be9657ec9002e528f4f17a5c43edc525a07f888f7b180c2afbf75e096c4f38a",
    ),
    (
        "pons_usdg_07",
        "0x39dBED3a2bd333467115dE45665cC57F813C4571",
        "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168",
        7000,
        140,
        "0x0000000000000000000000000000000000000000",
        "0x13f9ab4e07b7f222cf49ff8ae9d7cdd2f749546eb3f83bdd84b884e27dd5e49d",
    ),
    (
        "spy_usdg_03",
        "0x117cC2133c37B721F49de2a7a74833232b3B4c0C",
        "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168",
        3000,
        60,
        "0x0000000000000000000000000000000000000000",
        "0xfe2a80bb5618fd14984b92ca6d45bf5ba67443ddb1435e28b2e48df2fc1526cd",
    ),
    (
        "cashcat_usdg_0269",
        "0x020bfC650A365f8Bb26819DEaAbF3e21291018B4",
        "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168",
        2690,
        54,
        "0x0000000000000000000000000000000000000000",
        "0xa92a3df27a00a276183ff7265fd8affa11df1fe8bb23ddfaf13f6c879a3f818b",
    ),
    (
        "weth_usdg_001_native_eth",
        "0x0000000000000000000000000000000000000000",
        "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168",
        100,
        1,
        "0x0000000000000000000000000000000000000000",
        "0x24107d152f14a76d292123265ae3f3c71f863fc2f4ef7ba49d64e78d28ea379e",
    ),
]

SYNTHETIC_MANAGER = "0x1111111111111111111111111111111111115042"
SYNTHETIC_UNAUTHORIZED_MANAGER = "0x9999999999999999999999999999999999999999"
SYNTHETIC_HOOK = "0x4000000000000000000000000000000000000004"
ZERO_HOOK = "0x0000000000000000000000000000000000000000"


class TestLegacyV4PoolKeyObligations:
    """Rigorous tests for V4 PoolKey derivation, EVM Keccak-256 compliance, and invariants."""

    def test_six_canonical_pool_vectors_exact_keccak_derivation(self) -> None:
        """Verify all 6 legacy fixed vectors derive exact canonical 66-character EVM Keccak-256 poolIds.

        Validates against hardcoded expected poolIds and an independent reference implementation.
        """
        for name, c0, c1, fee, ts, hooks, expected_pid in LEGACY_SIX_CANONICAL_VECTORS:
            key = V4PoolKey(
                currency0=c0,
                currency1=c1,
                fee=fee,
                tick_spacing=ts,
                hooks=hooks,
            )
            computed_id = key.compute_pool_id()

            # Exact full-length 66-char match against hardcoded canonical hash
            assert computed_id == expected_pid.lower(), (
                f"Vector {name} pool_id mismatch: expected {expected_pid}, got {computed_id}"
            )
            assert len(computed_id) == 66
            assert computed_id.startswith("0x")

            # Validate against independent eth_abi and eth_utils reference
            ref_encoded = independent_abi_encode(
                ["address", "address", "uint24", "int24", "address"],
                [c0.lower(), c1.lower(), fee, ts, hooks.lower()],
            )
            independent_expected = "0x" + independent_keccak(ref_encoded).hex()
            assert computed_id == independent_expected, (
                f"Vector {name} failed independent Keccak-256 cross-validation"
            )

            # Property assertions
            assert key.is_dynamic_fee is False
            assert key.has_hooks is False
            assert key.fee == fee
            assert key.tick_spacing == ts

    def test_nist_sha3_mathematical_divergence_proof(self) -> None:
        """Prove that NIST SHA3-256 (defective implementation) systematically deviates from EVM Keccak-256.

        Demonstrates that hashlib.sha3_256 produces invalid poolIds for all 6 canonical vectors.
        """
        for name, c0, c1, fee, ts, hooks, expected_pid in LEGACY_SIX_CANONICAL_VECTORS:
            key = V4PoolKey(currency0=c0, currency1=c1, fee=fee, tick_spacing=ts, hooks=hooks)
            computed_id = key.compute_pool_id()

            # Pack identically to legacy defective hashlib.sha3_256 implementation
            c0_bytes = bytes.fromhex(c0[2:].lower().zfill(64))
            c1_bytes = bytes.fromhex(c1[2:].lower().zfill(64))
            fee_bytes = fee.to_bytes(32, byteorder="big")
            ts_bytes = (ts if ts >= 0 else ts + 2**256).to_bytes(32, byteorder="big")
            hooks_bytes = bytes.fromhex(hooks[2:].lower().zfill(64))
            packed = c0_bytes + c1_bytes + fee_bytes + ts_bytes + hooks_bytes

            erroneous_sha3 = "0x" + hashlib.sha3_256(packed).hexdigest()

            # SHA3-256 must NOT match canonical expected EVM poolId
            assert erroneous_sha3 != expected_pid.lower(), (
                f"Vector {name}: unexpected collision between NIST SHA3 and EVM Keccak"
            )
            # compute_pool_id() must NOT produce the erroneous SHA3-256 hash
            assert computed_id != erroneous_sha3, (
                f"Vector {name}: compute_pool_id() erroneously returned NIST SHA3-256 output"
            )

    def test_field_mutation_sensitivity(self) -> None:
        """Verify that mutating each 5-tuple field individually alters the derived poolId."""
        c0 = "0x2E8c31162b855A2ffa90F6F8634643Ad6F111e18"
        c1 = "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168"
        fee = 2300
        ts = 23
        hooks = ZERO_HOOK

        base_key = V4PoolKey(c0, c1, fee, ts, hooks)
        base_id = base_key.compute_pool_id()

        # 1. Mutate currency0
        c0_alt = "0x2e8c31162b855a2ffa90f6f8634643ad6f111e19"
        assert V4PoolKey(c0_alt, c1, fee, ts, hooks).compute_pool_id() != base_id

        # 2. Mutate currency1
        c1_alt = "0x5fc5360d0400a0fd4f2af552add042d716f1d169"
        assert V4PoolKey(c0, c1_alt, fee, ts, hooks).compute_pool_id() != base_id

        # 3. Mutate fee
        assert V4PoolKey(c0, c1, fee + 1, ts, hooks).compute_pool_id() != base_id

        # 4. Mutate tick_spacing
        assert V4PoolKey(c0, c1, fee, ts + 1, hooks).compute_pool_id() != base_id

        # 5. Mutate hooks
        assert V4PoolKey(c0, c1, fee, ts, SYNTHETIC_HOOK).compute_pool_id() != base_id

    def test_address_casing_invariance(self) -> None:
        """Verify mixed-case / checksummed address inputs derive identical canonical lowercase poolId."""
        name, c0, c1, fee, ts, hooks, expected_pid = LEGACY_SIX_CANONICAL_VECTORS[0]

        key_mixed = V4PoolKey(currency0=c0, currency1=c1, fee=fee, tick_spacing=ts, hooks=hooks)
        key_lower = V4PoolKey(
            currency0=c0.lower(),
            currency1=c1.lower(),
            fee=fee,
            tick_spacing=ts,
            hooks=hooks.lower(),
        )
        key_upper = V4PoolKey(
            currency0="0x" + c0[2:].upper(),
            currency1="0x" + c1[2:].upper(),
            fee=fee,
            tick_spacing=ts,
            hooks="0x" + hooks[2:].upper(),
        )

        id_mixed = key_mixed.compute_pool_id()
        id_lower = key_lower.compute_pool_id()
        id_upper = key_upper.compute_pool_id()

        assert id_mixed == id_lower == id_upper == expected_pid.lower()

    def test_strict_currency_order_fail_closed(self) -> None:
        """Verify Arc fails closed if currency0 >= currency1 (no silent reordering allowed)."""
        c0 = "0x2E8c31162b855A2ffa90F6F8634643Ad6F111e18"
        c1 = "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168"

        # Reversed order: currency0 > currency1
        with pytest.raises(ArcValidationError, match="currency0.*must be strictly less than currency1"):
            V4PoolKey(currency0=c1, currency1=c0, fee=3000, tick_spacing=60, hooks=ZERO_HOOK)

        # Equal currencies: currency0 == currency1
        with pytest.raises(ArcValidationError, match="currency0.*must be strictly less than currency1"):
            V4PoolKey(currency0=c0, currency1=c0, fee=3000, tick_spacing=60, hooks=ZERO_HOOK)

    def test_parameter_bounds_enforcement(self) -> None:
        """Verify fee bounds (0..0xFFFFFF) and positive tick_spacing enforcement."""
        c0 = "0x1000000000000000000000000000000000000001"
        c1 = "0x2000000000000000000000000000000000000002"

        # Negative tick_spacing
        with pytest.raises(ArcValidationError, match="tick_spacing must be positive"):
            V4PoolKey(currency0=c0, currency1=c1, fee=3000, tick_spacing=-1, hooks=ZERO_HOOK)

        # Zero tick_spacing
        with pytest.raises(ArcValidationError, match="tick_spacing must be positive"):
            V4PoolKey(currency0=c0, currency1=c1, fee=3000, tick_spacing=0, hooks=ZERO_HOOK)

        # Negative fee
        with pytest.raises(ArcValidationError, match="Invalid V4 fee"):
            V4PoolKey(currency0=c0, currency1=c1, fee=-1, tick_spacing=60, hooks=ZERO_HOOK)

        # Out-of-bounds fee (> 0xFFFFFF)
        with pytest.raises(ArcValidationError, match="Invalid V4 fee"):
            V4PoolKey(currency0=c0, currency1=c1, fee=0x1000000, tick_spacing=60, hooks=ZERO_HOOK)

    def test_dynamic_fee_and_missing_hooks_spec(self) -> None:
        """Verify dynamic fee and hook identification flags.

        Under Arc execution specification, pools with unverified hooks or dynamic fees
        must fail qualification for autonomous execution (DYNAMIC_FEE_ADAPTER_REQUIRED).
        """
        c0 = "0x1000000000000000000000000000000000000001"
        c1 = "0x2000000000000000000000000000000000000002"

        # Static fee, no hooks
        key_static = V4PoolKey(c0, c1, fee=3000, tick_spacing=60, hooks=ZERO_HOOK)
        assert key_static.is_dynamic_fee is False
        assert key_static.has_hooks is False

        # Dynamic fee, custom hook
        key_dynamic = V4PoolKey(
            c0, c1, fee=DYNAMIC_FEE_FLAG | 500, tick_spacing=60, hooks=SYNTHETIC_HOOK
        )
        assert key_dynamic.is_dynamic_fee is True
        assert key_dynamic.has_hooks is True


class TestLegacyV4DiscoveryAndLookupObligations:
    """Candidate tests for pool metadata lookup, casing normalization, and event alignment."""

    @pytest.fixture
    def engine(self) -> V4MarketDiscoveryEngine:
        dep_reg = DeploymentsRegistry(target_chain_id=5042)
        rec = ArcDeploymentRecord(
            name="arc_v4_pool_manager",
            role=ContractRole.MANAGER,
            address=SYNTHETIC_MANAGER,
            chain_id=5042,
            abi_hash="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
            source_proof="genesis:synthetic_v4_manager",
        )
        dep_reg.register(rec)
        return V4MarketDiscoveryEngine(chain_id=5042, deployments_registry=dep_reg)

    def test_get_v4_pool_case_insensitive_lookup(self, engine: V4MarketDiscoveryEngine) -> None:
        """Verify pool lookup by pool_id and manager address is strictly case-insensitive."""
        c0 = "0x1000000000000000000000000000000000000001"
        c1 = "0x2000000000000000000000000000000000000002"
        key = V4PoolKey(c0, c1, 2300, 23, ZERO_HOOK)
        pool_id = key.compute_pool_id()

        event = V4InitializeEvent(
            pool_id=pool_id,
            currency0=c0,
            currency1=c1,
            fee=2300,
            tick_spacing=23,
            hooks=ZERO_HOOK,
            manager_address=SYNTHETIC_MANAGER,
            block_number=1000,
            tx_hash="0x" + "aa" * 32,
        )
        discovered = engine.process_initialize(event)
        assert isinstance(discovered, V4DiscoveredPool)
        assert discovered.pool_id == pool_id.lower()

        # Query with uppercase manager and uppercase pool_id
        upper_pool = engine.get_pool(SYNTHETIC_MANAGER.upper(), pool_id.upper())
        # Query with lowercase manager and lowercase pool_id
        lower_pool = engine.get_pool(SYNTHETIC_MANAGER.lower(), pool_id.lower())

        assert upper_pool is not None
        assert lower_pool is not None
        assert upper_pool == lower_pool
        assert isinstance(upper_pool, V4DiscoveredPool)
        assert upper_pool.v4_key.tick_spacing == 23
        assert upper_pool.v4_key.fee == 2300
        assert upper_pool.v4_key.hooks == ZERO_HOOK

    def test_process_initialize_preserves_custom_tick_and_hooks(
        self, engine: V4MarketDiscoveryEngine
    ) -> None:
        """Verify discovery preserves custom tick_spacing=54 and custom hooks from initialize event."""
        c0 = "0x1000000000000000000000000000000000000001"
        c1 = "0x2000000000000000000000000000000000000002"
        key = V4PoolKey(c0, c1, 2690, 54, SYNTHETIC_HOOK)
        pool_id = key.compute_pool_id()

        event = V4InitializeEvent(
            pool_id=pool_id,
            currency0=c0,
            currency1=c1,
            fee=2690,
            tick_spacing=54,
            hooks=SYNTHETIC_HOOK,
            manager_address=SYNTHETIC_MANAGER,
            block_number=2000,
            tx_hash="0x" + "bb" * 32,
        )
        discovered = engine.process_initialize(event)
        assert isinstance(discovered, V4DiscoveredPool)
        assert discovered.v4_key.tick_spacing == 54
        assert discovered.v4_key.fee == 2690
        assert discovered.v4_key.hooks == SYNTHETIC_HOOK.lower()
        assert discovered.has_hooks is True

    def test_process_initialize_unauthorized_manager_rejected(
        self, engine: V4MarketDiscoveryEngine
    ) -> None:
        """Verify discovery rejects events emitted by unauthorized or unknown manager."""
        c0 = "0x1000000000000000000000000000000000000001"
        c1 = "0x2000000000000000000000000000000000000002"
        event = V4InitializeEvent(
            pool_id="0x" + "11" * 32,
            currency0=c0,
            currency1=c1,
            fee=3000,
            tick_spacing=60,
            hooks=ZERO_HOOK,
            manager_address=SYNTHETIC_UNAUTHORIZED_MANAGER,
            block_number=3000,
            tx_hash="0x" + "cc" * 32,
        )
        with pytest.raises(ArcMarketIneligibleError, match="Unauthorized or unknown PoolManager"):
            engine.process_initialize(event)
